# VICReg
vicreg:
  base_lr: 0.4
  projector: 2048-8196-8196-8196 # 768 for smoll
  weight_decay: 0.000001
  sim_coeff: 25
  std_coeff: 25
  cov_coeff: 1

  batch_size: 2048
  pretrained: 0

# Evaluation
evaluation:
  batch_size: 2048
  lr: 0.1
  weight_decay: 0.000001
  momentum: 0.9
  linear: 1
  class_balanced: 0

# training general
general:
  epochs: 4000
  num_workers: 16
  dataset: nsynth-intrument
  prefetch_factor: 1
  check_val_every_n_epoch: 20

  # hardrware
  accelerator: tpu
  devices: 8
  precision: bf16
  strategy: xla

  # Audio
  sample_rate: 22050
  n_samples: 65024
  mixing: 1

  # Mel Spectrogram
  n_fft: 1024
  win_length: 1024
  hop_length: 512
  f_min: 0
  f_max: 11050
  normalize: 1
