# VICReg
vicreg:
  base_lr: 0.2
  projector: 1000-1024 # 768 for smoll
  weight_decay: 0.000001
  sim_coeff: 25
  std_coeff: 25
  cov_coeff: 1

  batch_size: 128
  model: small
  pretrained: True

# Evaluation
evaluation:
  batch_size: 256
  lr: 0.001
  weight_decay : 0.000001
  linear: 1
  percentage: 1.0
  seed: 42

# training general
general: 
  epochs: 1
  num_workers: 16
  train_dataset: msd
  val_dataset: msd
  check_val_every_n_epoch: 1

  accelerator: tpu
  devices: 8
  precision: bf16-mixed
  strategy: xla

  sample_rate: 22050
  hop_length: 128
  win_length: 250
